const MINIMUM_PASSWORD_LENGTH = 8;
const MAXIMUM_PASSWORD_LENGTH = 128;

const NAME_FORM_FIELD = "name";
const EMAIL_FORM_FIELD = "email";
const PASSWORD_FORM_FIELD = "password";

export {
  MINIMUM_PASSWORD_LENGTH,
  MAXIMUM_PASSWORD_LENGTH,
  PASSWORD_FORM_FIELD,
  EMAIL_FORM_FIELD,
  NAME_FORM_FIELD,
};
