packages:
  - apps/*
  - demos/*
  - packages/*

catalog:
  "@radix-ui/react-dropdown-menu": ^2.1.16
  "@radix-ui/react-slot": ^1.2.4
  "@t3-oss/env-nextjs": ^0.13.8
  "@tailwindcss/postcss": ^4.1.17
  "@types/node": ^24.10.1
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  babel-plugin-react-compiler: ^1.0.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  drizzle-orm: ^0.44.7
  eslint: ^9.39.1
  lucide-react: ^0.555.0
  next: ^16.0.5
  next-themes: ^0.4.6
  postcss: ^8.5.6
  react: ^19.2.0
  react-dom: ^19.2.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.17
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  uuid: ^13.0.0
  zod: ^4.1.13

onlyBuiltDependencies:
  - lefthook
  - sharp
