packages:
  - apps/*
  - demos/*
  - packages/*

catalog:
  "@tailwindcss/postcss": ^4.1.17
  "@types/node": ^24.10.1
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  babel-plugin-react-compiler: ^1.0.0
  eslint: ^9.39.1
  next: ^16.0.5
  postcss: ^8.5.6
  react: ^19.2.0
  react-dom: ^19.2.0
  tailwindcss: ^4.1.17
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3

onlyBuiltDependencies:
  - lefthook
  - sharp
